const mangaData = [
  {
    id: 1,
    title: "Naruto",
    originalTitle: "ナルト",
    img: "/src/img/Naruto.webp",
    author: "Masashi Kishimoto",
    genre: "Nekketsu, action",
    type: "Shonen",
    themes: "Ninjas, drame, combats, art martial",
    "original editor:": "Shūeisha",
    frenchEditor: "Kana",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Shōnen Jump",
    numbersOfVolumesJapan: "72 ",
    numbersOfVolumesFrance: "72",
    publicationDatesJapan: "Du 21 Septembre 1999 au 10 Novembre 2014",
    publicationDatesFrance: "Entre Mars 2002 et Novembre 2016.",
    dateAdded: "2024-04-21",
    notation: 9.5,
    notationDate: "2024-04-21",
    review: "Un manga culte",
    reviewDate: "Mai",
    copyright: "NARUTO © 1999 by Masashi Kishimoto / SHUEISHA Inc.",
    summary:
      "Douze ans avant le début de la série, Kyûbi attaqua le village Konoha détruisant une grande partie du village et emportant de nombreuses vies. Le chef du village, le Quatrième Hokage, sacrifia sa vie pour sceller le Démon dans un nouveau-né, Naruto Uzumaki. Orphelin de l'attaque, Naruto a été évité par les villageois, qui, par peur et colère, le considéraient comme Kyûbi lui-même. Bien que le Troisième Hokage ait interdit de parler de tout ce qui concernait Kyûbi, les enfants - prenant exemple sur leurs parents - ont hérité de la même animosité envers Naruto. Dans sa soif d'être reconnu, Naruto jura qu'il deviendrait un jour le plus grand Hokage que le village ait jamais vu.",
    quickSummary:
      "Douze ans avant le début de la série, Kyûbi attaqua le village Konoha détruisant une grande partie du village et emportant de nombreuses vies.",
    urlFnac:
      "https://www.fnac.com/a1281224/Naruto-Tome-1-Naruto-Tome-1-avec-Sticker-euro-Masashi-Kishimoto",
  },
  {
    id: 2,
    title: "Jujutsu Kaisen",
    originalTitle: "呪術廻戦",
    img: "/src/img/Jujutsu-Kaisen.webp",
    author: "Gege Akutami",
    genre: "Action, dark fantasy",
    type: "Shonen",
    themes: "Ecole, Magie, Organisations secrètes,Paranormal, Yōkai",
    frenchEditor: "Ki-oon",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Shōnen Jump",
    numbersOfVolumesJapan: "30",
    numbersOfVolumesFrance: "30",
    publicationDatesJapan: "Depuis mars 2018",
    publicationDatesFrance: "Depuis 2020",
    dateAdded: "2024-04-21",
    notation: 9,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Yuji Itadori est un garçon doté d'une incroyable force physique qui mène pourtant une vie de lycéen tout à fait ordinaire. Un jour, pour sauver un camarade de classe attaqué par des fléaux, il mange le doigt du Roi des Fléaux et se fait posséder par l'esprit de ce dernier. Dès lors, ils ne font plus qu'un. Guidé par le plus puissant des exorcistes, Satoru Gojo, Yuji est admis à l'école d'exorcisme de Tokyo, une organisation qui combat les fléaux... C'est ainsi que commence le récit héroïque d'un garçon devenu un fléau pour exorciser un fléau, une vie qu'il n'a jamais pu quitter.",
    quickSummary:
      "Yuji Itadori est un garçon doté d'une incroyable force physique qui mène pourtant une vie de lycéen tout à fait ordinaire.",
    urlFnac:
      "https://www.fnac.com/a13634748/Jujutsu-Kaisen-Tome-01-Jujutsu-Kaisen-Gege-Akutami",
  },
  {
    id: 3,
    title: "One Piece Tome 1",
    originalTitle: "ワンピース",
    img: "/src/img/One piece.webp",
    author: "Eiichiro Oda",
    genre: "Aventure, Action, Fantaisie",
    type: "Shonen",
    themes: "Pirates, Liberté, Amitié, Trésor",
    frenchEditor: "Glénat",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Shōnen Jump",
    numbersOfVolumesJapan: "113",
    numbersOfVolumesFrance: "111",
    publicationDatesJapan: "Depuis 1997",
    publicationDatesFrance: "Depuis 2000",
    dateAdded: "2024-04-21",
    notation: 9.9,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Nous sommes à l'ère des pirates. Luffy, un garçon espiègle, rêve de devenir le roi des pirates en trouvant le “One Piece”, un fabuleux trésor. Seulement, Luffy a avalé un fruit du démon qui l'a transformé en homme élastique. Depuis, il est capable de contorsionner son corps dans tous les sens, mais il a perdu la faculté de nager. Avec l'aide de ses précieux amis, il va devoir affronter de redoutables pirates dans des aventures toujours plus rocambolesques.Également adapté en dessin animé pour la télévision et le cinéma, One Piece remporte un formidable succès à travers le monde. Les aventures de Luffy au chapeau de paille ont désormais gagné tous les lecteurs, qui se passionnent chaque trimestre pour les aventures exceptionnelles de leurs héros.",
    quickSummary:
      "Nous sommes à l'ère des pirates. Luffy, un garçon espiègle, rêve de devenir le roi des pirates en trouvant le “One Piece”, un fabuleux trésor",
    urlFnac:
      "https://www.fnac.com/a5843684/One-Piece-A-l-aube-d-une-grande-aventure-Tome-01-One-Piece-Edition-originale-Eiichiro-Oda",
  },
  {
    id: 4,
    title: "Demon Slayer",
    originalTitle: "鬼滅の刃",
    img: "/src/img/demon-slayers-1-6728cc7fc3b35418818000.webp",
    author: "Koyoharu Gotouge",
    genre: "Action, dark fantasy",
    type: "Shonen",
    themes: "Démons, Famille, Vengeance, Épées",
    frenchEditor: "Panini",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Shōnen Jump",
    numbersOfVolumesJapan: "23",
    numbersOfVolumesFrance: "23",
    publicationDatesJapan: "2016 - 2020",
    publicationDatesFrance: "2017 - 2021",
    dateAdded: "2024-04-21",
    notation: 8,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Après le massacre de sa famille par un démon, Tanjiro devient pourfendeur afin de sauver sa sœur Nezuko, transformée en créature démoniaque. Il affronte les Douze Lunes pour briser la malédiction.",
    quickSummary:
      "Après le massacre de sa famille par un démon, Tanjiro devient pourfendeur afin de sauver sa sœur Nezuko, transformée en créature démoniaque.",
    urlFnac:
      "https://www.fnac.com/a13631938/Demon-Slayer-Tome-01-Demon-Slayer-Koyoharu-Gotouge",
  },
  {
    id: 5,
    title: "Attack on Titan",
    originalTitle: "進撃の巨人",
    img: "/src/img/attaque-des-titans-1-pika.webp",
    author: "Hajime Isayama",
    genre: "Dark fantasy, Action, Drame",
    type: "Seinen",
    themes: "Guerre, Titans, Politique, Mystères",
    frenchEditor: "Pika",
    originalEditor: "Kodansha",
    publishingMagazine: "Bessatsu Shōnen Magazine",
    numbersOfVolumesJapan: "34",
    numbersOfVolumesFrance: "34",
    publicationDatesJapan: "2009 - 2021",
    publicationDatesFrance: "2013 - 2021",
    dateAdded: "2024-04-21",
    notation: 9.2,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Eren Jaeger rejoint l’armée pour combattre les Titans qui ont détruit sa ville. Mais derrière ces monstres se cachent des secrets capables de bouleverser l’humanité entière.",
    quickSummary:
      "Eren Jaeger rejoint l’armée pour combattre les Titans qui ont détruit sa ville. Mais derrière ces monstres se cachent des secrets capables de bouleverser l’humanité entière.",
    urlFnac:
      "https://www.fnac.com/a5671880/L-Attaque-des-Titans-Tome-01-L-Attaque-des-Titans-Hajime-Isayama",
  },
  {
    id: 6,
    title: "My Hero Academia",
    originalTitle: "僕のヒーローアカデミア",
    img: "/src/img/my-hero-academia-6723b2824d706624091469.webp",
    author: "Kohei Horikoshi",
    genre: "Action, Super-héros",
    type: "Shonen",
    themes: "École, Pouvoirs, Héroïsme, Société",
    frenchEditor: "Ki-oon",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Shōnen Jump",
    numbersOfVolumesJapan: "40",
    numbersOfVolumesFrance: "40",
    publicationDatesJapan: "Depuis 2014",
    publicationDatesFrance: "Depuis 2016",
    dateAdded: "2024-04-21",
    notation: 7.5,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Izuku Midoriya, né sans pouvoir dans un monde où ils sont la norme, reçoit l’héritage du plus grand héros. Il rejoint l’académie Yuei pour apprendre à devenir un symbole de paix.",
    quickSummary:
      "Izuku Midoriya, né sans pouvoir dans un monde où ils sont la norme, reçoit l’héritage du plus grand héros",
    urlFnac:
      "https://www.fnac.com/a9323419/My-Hero-Academia-Tome-01-My-Hero-Academia-Kohei-Horikoshi",
  },
  {
    id: 7,
    title: "Chainsaw Man",
    originalTitle: "チェンソーマン",
    img: "/src/img/chainsaw-man-tome1.webp",
    author: "Tatsuki Fujimoto",
    genre: "Action, horreur, dark fantasy",
    type: "Shonen",
    themes: "Démons, Violence, Société, Surréalisme",
    frenchEditor: "Kazé",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Shōnen Jump",
    numbersOfVolumesJapan: "17",
    numbersOfVolumesFrance: "17",
    publicationDatesJapan: "Depuis 2018",
    publicationDatesFrance: "Depuis 2020",
    dateAdded: "2024-04-21",
    notation: 8.3,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Denji fusionne avec son démon-tronçonneuse pour survivre dans un monde où les démons naissent des peurs humaines. Il rejoint la Sécurité Publique, mais découvre vite que les humains peuvent être pires que les monstres.",
    quickSummary:
      "Denji fusionne avec son démon-tronçonneuse pour survivre dans un monde où les démons naissent des peurs humaines.",
    urlFnac:
      "https://www.fnac.com/a14053777/Chainsaw-Man-Tome-01-Chainsaw-Man-Tatsuki-Fujimoto",
  },
  {
    id: 8,
    title: "Tokyo Revengers",
    originalTitle: "東京卍リベンジャーズ",
    img: "/src/img/tokyo-revengers-1-glenat.webp",
    author: "Ken Wakui",
    genre: "Action, Drame, Voyage temporel",
    type: "Shonen",
    themes: "Gangs, Amitié, Destin, Rédemption",
    frenchEditor: "Glénat",
    originalEditor: "Kodansha",
    publishingMagazine: "Weekly Shōnen Magazine",
    numbersOfVolumesJapan: "31",
    numbersOfVolumesFrance: "31",
    publicationDatesJapan: "2017 - 2022",
    publicationDatesFrance: "2019 - 2023",
    dateAdded: "2024-04-21",
    notation: 7.8,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Takemichi retourne dans le passé pour empêcher la mort de son amour d’enfance. Il infiltre le Tokyo Manji Gang et tente de changer un futur tragique.",
    quickSummary:
      "Takemichi retourne dans le passé pour empêcher la mort de son amour d’enfance. Il infiltre le Tokyo Manji Gang et tente de changer un futur tragique",
    urlFnac:
      "https://www.fnac.com/a13176940/Tokyo-Revengers-Tome-01-Tokyo-Revengers-Ken-Wakui",
  },
  {
    id: 9,
    title: "Blue Lock",
    originalTitle: "ブルーロック",
    img: "/src/img/blue-lock-tome-1.webp",
    author: "Muneyuki Kaneshiro & Yusuke Nomura",
    genre: "Sport, Psychologie",
    type: "Shonen",
    themes: "Football, Compétition, Égo, Dépassement",
    frenchEditor: "Pika",
    originalEditor: "Kodansha",
    publishingMagazine: "Weekly Shōnen Magazine",
    numbersOfVolumesJapan: "29",
    numbersOfVolumesFrance: "29",
    publicationDatesJapan: "Depuis 2018",
    publicationDatesFrance: "Depuis 2021",
    dateAdded: "2024-04-21",
    notation: 8.1,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Yoichi Isagi rejoint Blue Lock, un programme extrême visant à créer l’attaquant ultime du Japon. Dans cet environnement impitoyable, seul l’égoïsme mène à la victoire.",
    quickSummary:
      "Yoichi Isagi rejoint Blue Lock, un programme extrême visant à créer l’attaquant ultime du Japon. Dans cet environnement impitoyable, seul l’égoïsme mène à la victoire",
    urlFnac:
      "https://www.fnac.com/a15210950/Blue-Lock-Tome-01-Blue-Lock-Yusuke-Nomura",
  },
  {
    id: 10,
    title: "Solo Leveling",
    originalTitle: "나 혼자만 레벨업",
    img: "/src/img/solo-leveling-tome1.webp",
    author: "Chugong",
    genre: "Action, Fantaisie, RPG",
    type: "Webtoon",
    themes: "Donjons, Chasseurs, Évolution, Système",
    frenchEditor: "Kbooks",
    originalEditor: "D&C Media",
    publishingMagazine: "KakaoPage",
    numbersOfVolumesJapan: "8 (édition reliée)",
    numbersOfVolumesFrance: "8",
    publicationDatesJapan: "2018 - 2021",
    publicationDatesFrance: "2021 - 2023",
    dateAdded: "2024-04-21",
    notation: 8.9,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Sung Jinwoo, le plus faible des chasseurs, survit à un donjon mortel et obtient la capacité unique de devenir plus fort sans limite. Il grimpe les niveaux pour protéger les siens et affronter des forces qui dépassent l’humanité.",
    quickSummary:
      "Sung Jinwoo, le plus faible des chasseurs, survit à un donjon mortel et obtient la capacité unique de devenir plus fort sans limite. Il grimpe les niveaux pour protéger les siens et affronter des forces qui dépassent l’humanité",
    urlFnac:
      "https://www.fnac.com/a15626044/Solo-Leveling-Tome-01-Solo-Leveling-Chugong",
  },
  {
    id: 11,
    title: "Fullmetal Alchemist",
    originalTitle: "鋼の錬金術師",
    img: "/src/img/fullmetal_01.webp",
    author: "Hiromu Arakawa",
    genre: "Action, aventure, fantasy",
    type: "Shonen",
    themes: "Alchimie, Fraternité, Guerre, Philosophie",
    frenchEditor: "Kurokawa",
    originalEditor: "Shūeisha",
    publishingMagazine: "Monthly Shōnen Gangan",
    numbersOfVolumesJapan: "27",
    numbersOfVolumesFrance: "27",
    publicationDatesJapan: "2001 - 2010",
    publicationDatesFrance: "2005 - 2011",
    dateAdded: "2024-04-21",
    notation: 9.9,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Après une transmutation interdite, Edward et Alphonse Elric cherchent la Pierre Philosophale pour retrouver leurs corps. Leur quête les mène au cœur d’un complot qui menace tout le pays d’Amestris.",
    quickSummary:
      "Après une transmutation interdite, Edward et Alphonse Elric cherchent la Pierre Philosophale pour retrouver leurs corps",
  },
  {
    id: 12,
    title: "Death Note",
    originalTitle: "デスノート",
    img: "/src/img/death-note-tome-1.webp",
    author: "Tsugumi Ohba & Takeshi Obata",
    genre: "Thriller, surnaturel",
    type: "Shonen",
    themes: "Justice, Morale, Manipulation, Enquête",
    frenchEditor: "Kana",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Shōnen Jump",
    numbersOfVolumesJapan: "12",
    numbersOfVolumesFrance: "12",
    publicationDatesJapan: "2003 - 2006",
    publicationDatesFrance: "2007 - 2008",
    dateAdded: "2024-04-21",
    notation: 9.9,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Light Yagami découvre un carnet capable de tuer quiconque y voit son nom inscrit. Il entreprend de purifier le monde, mais un détective prodige surnommé L se lance à sa poursuite.",
    quickSummary:
      "Light Yagami découvre un carnet capable de tuer quiconque y voit son nom inscrit",
    urlFnac:
      "https://www.fnac.com/a1911412/Death-Note-Tome-1-Tome-1-Death-Note-Tsugumi-Ohba",
  },
  {
    id: 13,
    title: "Hunter x Hunter",
    originalTitle: "ハンター×ハンター",
    img: "/src/img/Hunter-X-Hunter-t1-kana.webp",
    author: "Yoshihiro Togashi",
    genre: "Aventure, action, fantasy",
    type: "Shonen",
    themes: "Exploration, Pouvoirs, Amitié, Quêtes",
    frenchEditor: "Kana",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Shōnen Jump",
    numbersOfVolumesJapan: "37",
    numbersOfVolumesFrance: "37",
    publicationDatesJapan: "Depuis 1998",
    publicationDatesFrance: "Depuis 2000",
    dateAdded: "2024-04-21",
    notation: 9.1,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Gon Freecss devient Hunter pour retrouver son père disparu. Sa route croise celle de Killua, Kurapika et Leolio, et ensemble ils affrontent des épreuves où le Nen fait la loi.",
    quickSummary:
      "Gon Freecss devient Hunter pour retrouver son père disparu. Sa route croise celle de Killua, Kurapika et Leolio, et ensemble ils affrontent des épreuves où le Nen fait la loi.",
    urlFnac:
      "https://www.fnac.com/a867588/Hunter-X-Hunter-Tome-1-Hunter-X-Hunter-Yoshihiro-Togashi",
  },
  {
    id: 14,
    title: "Black Clover",
    originalTitle: "ブラッククローバー",
    img: "/src/img/black-clover-t01-673f150b7a5b5944839860.webp",
    author: "Yūki Tabata",
    genre: "Action, fantasy",
    type: "Shonen",
    themes: "Magie, Rivalité, Destin, Royaume",
    frenchEditor: "Kazé",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Shōnen Jump",
    numbersOfVolumesJapan: "36",
    numbersOfVolumesFrance: "36",
    publicationDatesJapan: "Depuis 2015",
    publicationDatesFrance: "Depuis 2017",
    dateAdded: "2024-04-21",
    notation: 7.6,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Asta, né sans magie dans un monde où elle est reine, rêve de devenir Empereur-Mage. Armé d’un grimoire d’anti-magie, il défie son destin aux côtés de son rival Yuno.",
    quickSummary:
      "Asta, né sans magie dans un monde où elle est reine, rêve de devenir Empereur-Mage. Armé d’un grimoire d’anti-magie, il défie son destin aux côtés de son rival Yuno.",
    urlFnac:
      "https://www.fnac.com/a9693123/Black-Clover-Tome-01-Black-Clover-Yuki-Tabata",
  },
  {
    id: 15,
    title: "Fairy Tail",
    originalTitle: "フェアリーテイル",
    img: "/src/img/fairy_tail_01.webp",
    author: "Hiro Mashima",
    genre: "Aventure, fantasy",
    type: "Shonen",
    themes: "Guildes, Magie, Amitié, Quêtes",
    frenchEditor: "Pika",
    originalEditor: "Kodansha",
    publishingMagazine: "Weekly Shōnen Magazine",
    numbersOfVolumesJapan: "63",
    numbersOfVolumesFrance: "63",
    publicationDatesJapan: "2006 - 2017",
    publicationDatesFrance: "2008 - 2018",
    dateAdded: "2024-04-21",
    notation: 7.4,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Lucy rejoint la guilde Fairy Tail et fait équipe avec Natsu, un mage de feu élevé par un dragon. Ensemble, ils accomplissent des missions périlleuses et affrontent des ennemis redoutables.",
    quickSummary:
      "Lucy rejoint la guilde Fairy Tail et fait équipe avec Natsu, un mage de feu élevé par un dragon. Ensemble, ils accomplissent des missions périlleuses et affrontent des ennemis redoutables.",
    urlFnac:
      "https://www.fnac.com/a2261858/Fairy-Tail-Tome-01-Fairy-Tail-Hiro-Mashima",
  },
  {
    id: 16,
    title: "Dr. Stone",
    originalTitle: "ドクターストーン",
    img: "/src/img/dr-stone-manga-glenat-vol1.webp",
    author: "Riichiro Inagaki & Boichi",
    genre: "Science-fiction, aventure",
    type: "Shonen",
    themes: "Science, Survie, Civilisation, Ingéniosité",
    frenchEditor: "Glénat",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Shōnen Jump",
    numbersOfVolumesJapan: "26",
    numbersOfVolumesFrance: "26",
    publicationDatesJapan: "2017 - 2022",
    publicationDatesFrance: "2018 - 2023",
    dateAdded: "2024-04-21",
    notation: 8,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Après que l’humanité a été pétrifiée pendant des millénaires, Senku se réveille dans un monde sauvage. Il entreprend de reconstruire la civilisation grâce à la science.",
    quickSummary:
      "Après que l’humanité a été pétrifiée pendant des millénaires, Senku se réveille dans un monde sauvage. Il entreprend de reconstruire la civilisation grâce à la science.",
    urlFnac:
      "https://www.fnac.com/a11233866/Dr-Stone-Stone-World-Tome-01-Dr-Stone-Riichiro-Inagaki",
  },
  {
    id: 17,
    title: "Fire Force",
    originalTitle: "炎炎ノ消防隊",
    img: "/src/img/fire-force-1-kana.webp",
    author: "Atsushi Ōkubo",
    genre: "Action, dark fantasy",
    type: "Shonen",
    themes: "Incendies, Démons, Religion, Conspiration",
    frenchEditor: "Kana",
    originalEditor: "Kodansha",
    publishingMagazine: "Weekly Shōnen Magazine",
    numbersOfVolumesJapan: "34",
    numbersOfVolumesFrance: "34",
    publicationDatesJapan: "2015 - 2022",
    publicationDatesFrance: "2017 - 2023",
    dateAdded: "2024-04-21",
    notation: 7.7,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Shinra Kusakabe rejoint la Fire Force, une unité spéciale chargée d’éteindre les humains transformés en torches vivantes. Il découvre vite que son passé est lié à un complot brûlant.",
    quickSummary:
      "Shinra Kusakabe rejoint la Fire Force, une unité spéciale chargée d’éteindre les humains transformés en torches vivantes. Il découvre vite que son passé est lié à un complot brûlant.",
    urlFnac:
      "https://www.fnac.com/a10296100/Fire-Force-Tome-1-Fire-Force-Atsushi-Ohkubo",
  },
  {
    id: 18,
    title: "The Promised Neverland",
    originalTitle: "約束のネバーランド",
    img: "/src/img/promised-neverland-1-kaze.webp",
    author: "Kaiu Shirai & Posuka Demizu",
    genre: "Thriller, dark fantasy",
    type: "Shonen",
    themes: "Évasion, Enfants, Manipulation, Mystère",
    frenchEditor: "Kazé",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Shōnen Jump",
    numbersOfVolumesJapan: "20",
    numbersOfVolumesFrance: "20",
    publicationDatesJapan: "2016 - 2020",
    publicationDatesFrance: "2018 - 2021",
    dateAdded: "2024-04-21",
    notation: 8.4,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Emma découvre que l’orphelinat où elle vit cache un sombre secret. Avec Norman et Ray, elle prépare une évasion risquée pour sauver les enfants.",
    quickSummary:
      "Emma découvre que l’orphelinat où elle vit cache un sombre secret. Avec Norman et Ray, elle prépare une évasion risquée pour sauver les enfants.",
    urlFnac:
      "https://www.fnac.com/a11237041/The-Promised-Neverland-Tome-01-The-Promised-Neverland-Posuka-Demizu",
  },
  {
    id: 19,
    title: "Spy x Family",
    originalTitle: "スパイファミリー",
    img: "/src/img/Spy-Family-1-kurokawa.webp",
    author: "Tatsuya Endo",
    genre: "Comédie, action",
    type: "Shonen",
    themes: "Espionnage, Famille, Secrets, Politique",
    frenchEditor: "Kurokawa",
    originalEditor: "Shūeisha",
    publishingMagazine: "Shōnen Jump+",
    numbersOfVolumesJapan: "13",
    numbersOfVolumesFrance: "13",
    publicationDatesJapan: "Depuis 2019",
    publicationDatesFrance: "Depuis 2020",
    dateAdded: "2024-04-21",
    notation: 8.2,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Pour accomplir sa mission, l’espion Twilight doit former une famille factice. Il ignore que sa femme est une tueuse à gages et que sa fille lit dans les pensées.",
    quickSummary:
      "Pour accomplir sa mission, l’espion Twilight doit former une famille factice. Il ignore que sa femme est une tueuse à gages et que sa fille lit dans les pensées.",
    urlFnac:
      "https://www.fnac.com/a14859038/Spy-x-Family-Tome-1-Spy-x-Family-Tatsuya-Endo",
  },
  {
    id: 20,
    title: "Vinland Saga",
    originalTitle: "ヴィンランド・サガ",
    img: "/src/img/vinland_saga01.webp",
    author: "Makoto Yukimura",
    genre: "Historique, drame, action",
    type: "Seinen",
    themes: "Vikings, Vengeance, Guerre, Exploration",
    frenchEditor: "Kurokawa",
    originalEditor: "Kodansha",
    publishingMagazine: "Monthly Afternoon",
    numbersOfVolumesJapan: "27",
    numbersOfVolumesFrance: "27",
    publicationDatesJapan: "Depuis 2005",
    publicationDatesFrance: "Depuis 2009",
    dateAdded: "2024-04-21",
    notation: 9.1,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Thorfinn, fils d’un grand guerrier, cherche à venger son père. Sa quête le mène au cœur des conflits vikings et à la découverte d’un idéal de paix.",
    quickSummary:
      "Thorfinn, fils d’un grand guerrier, cherche à venger son père. Sa quête le mène au cœur des conflits vikings et à la découverte d’un idéal de paix.",
    urlFnac:
      "https://www.fnac.com/a2518109/Vinland-saga-Tome-1-Vinland-Saga-Makoto-Yukimura",
  },
  {
    id: 21,
    title: "Moriarty the Patriot",
    originalTitle: "憂国のモリアーティ",
    img: "/src/img/moriarty-1-kana.webp",
    author: "Ryōsuke Takeuchi & Hikaru Miyoshi",
    genre: "Thriller, historique",
    type: "Shonen",
    themes: "Enquête, Justice sociale, Crime, Angleterre victorienne",
    frenchEditor: "Kana",
    originalEditor: "Shūeisha",
    publishingMagazine: "Jump SQ",
    numbersOfVolumesJapan: "19",
    numbersOfVolumesFrance: "19",
    publicationDatesJapan: "2016 - 2023",
    publicationDatesFrance: "2017 - 2024",
    dateAdded: "2024-04-21",
    notation: 8,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "William Moriarty veut renverser l’ordre social injuste de l’Angleterre victorienne. Il orchestre des crimes parfaits pour punir les nobles corrompus.",
    quickSummary:
      "William Moriarty veut renverser l’ordre social injuste de l’Angleterre victorienne. Il orchestre des crimes parfaits pour punir les nobles corrompus.",
    urlFnac:
      "https://www.fnac.com/a11290769/Moriarty-Tome-1-Moriarty-Ryosuke-Takeuchi",
  },
  {
    id: 22,
    title: "Mushoku Tensei",
    originalTitle: "無職転生",
    img: "/src/img/mushoku-tensei-1-doki.webp",
    author: "Rifujin na Magonote",
    genre: "Fantasy, isekai",
    type: "Seinen",
    themes: "Renaissance, Magie, Destin, Aventure",
    frenchEditor: "Doki-Doki",
    originalEditor: "Media Factory",
    publishingMagazine: "Comic Flapper",
    numbersOfVolumesJapan: "19",
    numbersOfVolumesFrance: "19",
    publicationDatesJapan: "Depuis 2014",
    publicationDatesFrance: "Depuis 2017",
    dateAdded: "2024-04-21",
    notation: 7.9,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Un homme réincarné dans un monde magique décide de vivre sans regrets. Sous le nom de Rudeus, il développe un talent exceptionnel pour la magie.",
    quickSummary:
      "Un homme réincarné dans un monde magique décide de vivre sans regrets. Sous le nom de Rudeus, il développe un talent exceptionnel pour la magie.",
    urlFnac:
      "https://www.fnac.com/a10285743/Mushoku-Tensei-Tome-1-Mushoku-Tensei-vol-01-Yuka-Fujikawa",
  },
  {
    id: 23,
    title: "Frieren",
    originalTitle: "葬送のフリーレン",
    img: "/src/img/frieren-t-1.webp",
    author: "Kanehito Yamada & Tsukasa Abe",
    genre: "Fantasy, aventure",
    type: "Shonen",
    themes: "Immortalité, Mémoire, Voyage, Amitié",
    frenchEditor: "Ki-oon",
    originalEditor: "Shogakukan",
    publishingMagazine: "Weekly Shōnen Sunday",
    numbersOfVolumesJapan: "13",
    numbersOfVolumesFrance: "13",
    publicationDatesJapan: "Depuis 2020",
    publicationDatesFrance: "Depuis 2022",
    dateAdded: "2024-04-21",
    notation: 9.4,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Après la mort de ses anciens compagnons, l’elfe Frieren entreprend un voyage pour comprendre les émotions humaines et honorer leur mémoire.",
    quickSummary:
      "Après la mort de ses anciens compagnons, l’elfe Frieren entreprend un voyage pour comprendre les émotions humaines et honorer leur mémoire.",
    urlFnac:
      "https://www.fnac.com/a16509319/Frieren-Tome-01-Frieren-Kanehito-Yamada",
  },
  {
    id: 24,
    title: "Berserk",
    originalTitle: "ベルセルク",
    img: "/src/img/berserk-tome-01-670d3545b3420135806880.webp",
    author: "Kentaro Miura",
    genre: "Dark fantasy, drame",
    type: "Seinen",
    themes: "Démons, Tragédie, Destin, Violence",
    frenchEditor: "Glénat",
    originalEditor: "Hakusensha",
    publishingMagazine: "Young Animal",
    numbersOfVolumesJapan: "41",
    numbersOfVolumesFrance: "41",
    publicationDatesJapan: "1989 - 2021",
    publicationDatesFrance: "1996 - 2022",
    dateAdded: "2024-04-21",
    notation: 9.7,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Guts, mercenaire marqué par le destin, lutte contre des forces démoniaques après une trahison qui a bouleversé son existence. Sa quête de vengeance devient une lutte pour sa propre humanité.",
    quickSummary:
      "Guts, mercenaire marqué par le destin, lutte contre des forces démoniaques après une trahison qui a bouleversé son existence.",
    urlFnac:
      "https://www.fnac.com/a10206356/Berserk-Tome-01-Berserk-Nouvelle-edition-Kentaro-Miura",
  },
  {
    id: 25,
    title: "Made in Abyss",
    originalTitle: "メイドインアビス",
    img: "/src/img/made-in-abyss-1-ototo.webp",
    author: "Akihito Tsukushi",
    genre: "Aventure, dark fantasy",
    type: "Seinen",
    themes: "Exploration, Mystères, Enfance, Danger",
    frenchEditor: "Ototo",
    originalEditor: "Takeshobo",
    publishingMagazine: "Web Comic Gamma",
    numbersOfVolumesJapan: "12",
    numbersOfVolumesFrance: "12",
    publicationDatesJapan: "Depuis 2012",
    publicationDatesFrance: "Depuis 2018",
    dateAdded: "2024-04-21",
    notation: 8.8,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Riko descend dans l’Abysse, un gouffre rempli de créatures et de reliques, pour retrouver sa mère. Elle est accompagnée de Reg, un mystérieux garçon mécanique.",
    quickSummary:
      "Riko descend dans l’Abysse, un gouffre rempli de créatures et de reliques, pour retrouver sa mère. Elle est accompagnée de Reg, un mystérieux garçon mécanique.",
    urlFnac:
      "https://www.fnac.com/a11559752/Made-in-Abyss-Tome-01-Made-in-abyss-Akihito-Tsukushi",
  },
  {
    id: 26,
    title: "Dandadan",
    originalTitle: "ダンダダン",
    img: "/src/img/dandadan-t01-6728be6a531a6687708990.webp",
    author: "Yukinobu Tatsu",
    genre: "Action, comédie, surnaturel",
    type: "Shonen",
    themes: "Extraterrestres, Fantômes, Amitié, Romance",
    frenchEditor: "Crunchyroll",
    originalEditor: "Shūeisha",
    publishingMagazine: "Shōnen Jump+",
    numbersOfVolumesJapan: "14",
    numbersOfVolumesFrance: "14",
    publicationDatesJapan: "Depuis 2021",
    publicationDatesFrance: "Depuis 2022",
    dateAdded: "2024-04-21",
    notation: 8,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Momo et Okarun se retrouvent mêlés à des phénomènes étranges mêlant aliens et esprits. Leur duo improbable affronte des menaces aussi dangereuses que loufoques.",
    quickSummary:
      "Momo et Okarun se retrouvent mêlés à des phénomènes étranges mêlant aliens et esprits. Leur duo improbable affronte des menaces aussi dangereuses que loufoques.",
    urlFnac:
      "https://www.fnac.com/SearchResult/ResultList.aspx?Search=dandadan+tome+1&sft=1&sa=1",
  },
  {
    id: 27,
    title: "Kaiju No. 8",
    originalTitle: "怪獣8号",
    img: "/src/img/kaiju-n8-1-kaze.webp",
    author: "Naoya Matsumoto",
    genre: "Action, science-fiction",
    type: "Shonen",
    themes: "Monstres, Armée, Transformation, Héroïsme",
    frenchEditor: "Kazé",
    originalEditor: "Shūeisha",
    publishingMagazine: "Shōnen Jump+",
    numbersOfVolumesJapan: "12",
    numbersOfVolumesFrance: "12",
    publicationDatesJapan: "Depuis 2020",
    publicationDatesFrance: "Depuis 2021",
    dateAdded: "2024-04-21",
    notation: 8.5,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Kafka Hibino, employé d’entretien, devient capable de se transformer en kaiju. Il rejoint les Forces de Défense pour combattre les monstres qui ravagent le Japon.",
    quickSummary:
      "Kafka Hibino, employé d’entretien, devient capable de se transformer en kaiju. Il rejoint les Forces de Défense pour combattre les monstres qui ravagent le Japon.",
  },
  {
    id: 28,
    title: "Sakamoto Days",
    originalTitle: "サカモトデイズ",
    img: "/src/img/Sakamoto_Days_1_glenat_temp.webp",
    author: "Yuto Suzuki",
    genre: "Action, comédie",
    type: "Shonen",
    themes: "Assassins, Famille, Rédemption, Humour",
    frenchEditor: "Glénat",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Shōnen Jump",
    numbersOfVolumesJapan: "16",
    numbersOfVolumesFrance: "16",
    publicationDatesJapan: "Depuis 2020",
    publicationDatesFrance: "Depuis 2022",
    dateAdded: "2024-04-21",
    notation: 8,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Taro Sakamoto, ancien tueur légendaire devenu père de famille, reprend les armes pour protéger ses proches. Entre humour et combats explosifs, il prouve qu’on peut être un héros même derrière un comptoir.",
    quickSummary:
      "Taro Sakamoto, ancien tueur légendaire devenu père de famille, reprend les armes pour protéger ses proches. Entre humour et combats explosifs, il prouve qu’on peut être un héros même derrière un comptoir.",
  },
  {
    id: 29,
    title: "Hell's Paradise",
    originalTitle: "地獄楽",
    img: "/src/img/hell-s-paradise-1-kaze.webp",
    author: "Yuji Kaku",
    genre: "Action, dark fantasy",
    type: "Shonen",
    themes: "Ninja, Immortalité, Île mystérieuse, Survie",
    frenchEditor: "Kazé",
    originalEditor: "Shūeisha",
    publishingMagazine: "Shōnen Jump+",
    numbersOfVolumesJapan: "13",
    numbersOfVolumesFrance: "13",
    publicationDatesJapan: "2018 - 2021",
    publicationDatesFrance: "2020 - 2022",
    dateAdded: "2024-04-21",
    notation: 8.2,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Gabimaru, ninja condamné à mort, se voit offrir la liberté s’il récupère un élixir d’immortalité sur une île infernale. Il y découvre un paradis aussi beau que mortel.",
    quickSummary:
      "Gabimaru, ninja condamné à mort, se voit offrir la liberté s’il récupère un élixir d’immortalité sur une île infernale. Il y découvre un paradis aussi beau que mortel.",
  },
  {
    id: 30,
    title: "Mashle",
    originalTitle: "マッシュル",
    img: "/src/img/mashle-1-kaze.webp",
    author: "Hajime Komoto",
    genre: "Comédie, action, fantasy",
    type: "Shonen",
    themes: "Magie, École, Force physique, Parodie",
    frenchEditor: "Kazé",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Shōnen Jump",
    numbersOfVolumesJapan: "18",
    numbersOfVolumesFrance: "18",
    publicationDatesJapan: "2020 - 2023",
    publicationDatesFrance: "2021 - 2024",
    dateAdded: "2024-04-21",
    notation: 7.9,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Dans un monde où la magie règne, Mash Burnedead n’a aucun pouvoir. Il compense avec une force physique absurde et vise le titre suprême dans une école de magie.",
    quickSummary:
      "Dans un monde où la magie règne, Mash Burnedead n’a aucun pouvoir. Il compense avec une force physique absurde et vise le titre suprême dans une école de magie.",
  },
  {
    id: 31,
    title: "Radiant",
    originalTitle: "Radiant",
    img: "/src/img/radiant-1-ankama.webp",
    author: "Tony Valente",
    genre: "Fantasy, aventure",
    type: "Shonen",
    themes: "Magie, Quête, Corruption, Monstres",
    frenchEditor: "Ankama",
    originalEditor: "Ankama",
    publishingMagazine: "France (puis Japon)",
    numbersOfVolumesJapan: "17",
    numbersOfVolumesFrance: "17",
    publicationDatesJapan: "Depuis 2015",
    publicationDatesFrance: "Depuis 2015",
    dateAdded: "2024-04-21",
    notation: 8,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Seth, jeune sorcier infecté par les Némésis, cherche la source de ces monstres : le Radiant. Sa quête l’oppose à une société qui craint et rejette les sorciers.",
    quickSummary:
      "Seth, jeune sorcier infecté par les Némésis, cherche la source de ces monstres : le Radiant. Sa quête l’oppose à une société qui craint et rejette les sorciers.",
  },
  {
    id: 32,
    title: "To Your Eternity",
    originalTitle: "不滅のあなたへ",
    img: "/src/img/to-your-eternity-1-pika.webp",
    author: "Yoshitoki Ōima",
    genre: "Drame, fantasy",
    type: "Shonen",
    themes: "Immortalité, Humanité, Voyage, Émotions",
    frenchEditor: "Pika",
    originalEditor: "Kodansha",
    publishingMagazine: "Weekly Shōnen Magazine",
    numbersOfVolumesJapan: "21",
    numbersOfVolumesFrance: "21",
    publicationDatesJapan: "Depuis 2016",
    publicationDatesFrance: "Depuis 2017",
    dateAdded: "2024-04-21",
    notation: 9,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Une entité immortelle prend forme humaine et découvre le monde à travers les rencontres, les pertes et les liens qu’elle tisse au fil du temps.",
    quickSummary:
      "Une entité immortelle prend forme humaine et découvre le monde à travers les rencontres, les pertes et les liens qu’elle tisse au fil du temps.",
  },
  {
    id: 33,
    title: "Seraph of the End",
    originalTitle: "終わりのセラフ",
    img: "/src/img/seraph-of-the-end-1-kana.webp",
    author: "Takaya Kagami & Yamato Yamamoto",
    genre: "Dark fantasy, action",
    type: "Shonen",
    themes: "Vampires, Apocalypse, Armée, Amitié",
    frenchEditor: "Kana",
    originalEditor: "Shūeisha",
    publishingMagazine: "Jump SQ",
    numbersOfVolumesJapan: "31",
    numbersOfVolumesFrance: "31",
    publicationDatesJapan: "Depuis 2012",
    publicationDatesFrance: "Depuis 2014",
    dateAdded: "2024-04-21",
    notation: 7.8,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Après qu’un virus a décimé les adultes, les vampires ont réduit les enfants en esclavage. Yuichiro rejoint une unité d’élite pour se venger et libérer son ami.",
    quickSummary:
      "Après qu’un virus a décimé les adultes, les vampires ont réduit les enfants en esclavage. Yuichiro rejoint une unité d’élite pour se venger et libérer son ami.",
  },
  {
    id: 34,
    title: "Golden Kamui",
    originalTitle: "ゴールデンカムイ",
    img: "/src/img/golden-kamui-1-ki-oon.webp",
    author: "Satoru Noda",
    genre: "Historique, aventure",
    type: "Seinen",
    themes: "Survie, Trésor, Culture Aïnou, Guerre",
    frenchEditor: "Ki-oon",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Young Jump",
    numbersOfVolumesJapan: "31",
    numbersOfVolumesFrance: "31",
    publicationDatesJapan: "2014 - 2022",
    publicationDatesFrance: "2016 - 2023",
    dateAdded: "2024-04-21",
    notation: 9,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Saichi Sugimoto, vétéran de guerre, part à la recherche d’un trésor caché en Hokkaido. Il fait équipe avec Asirpa, une jeune Aïnou, pour survivre aux dangers de la nature et des criminels.",
    quickSummary:
      "Saichi Sugimoto, vétéran de guerre, part à la recherche d’un trésor caché en Hokkaido. Il fait équipe avec Asirpa, une jeune Aïnou, pour survivre aux dangers de la nature et des criminels.",
  },
  {
    id: 35,
    title: "Blue Period",
    originalTitle: "ブルーピリオド",
    img: "/src/img/blue-period-t1-pika.webp",
    author: "Tsubasa Yamaguchi",
    genre: "Drame, tranche de vie",
    type: "Seinen",
    themes: "Art, Études, Passion, Identité",
    frenchEditor: "Pika",
    originalEditor: "Kodansha",
    publishingMagazine: "Monthly Afternoon",
    numbersOfVolumesJapan: "15",
    numbersOfVolumesFrance: "15",
    publicationDatesJapan: "Depuis 2017",
    publicationDatesFrance: "Depuis 2020",
    dateAdded: "2024-04-21",
    notation: 8.6,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Yatora, excellent élève mais sans passion, découvre la peinture et décide de viser la plus prestigieuse école d’art du Japon. Son parcours est aussi exigeant que révélateur.",
    quickSummary:
      "Yatora, excellent élève mais sans passion, découvre la peinture et décide de viser la plus prestigieuse école d’art du Japon. Son parcours est aussi exigeant que révélateur.",
  },
  {
    id: 36,
    title: "Oshi no Ko",
    originalTitle: "【推しの子】",
    img: "/src/img/Oshi_no_Ko_1_kurokawa.webp",
    author: "Aka Akasaka & Mengo Yokoyari",
    genre: "Drame, show-business, mystère",
    type: "Seinen",
    themes: "Idols, Réincarnation, Médias, Secrets",
    frenchEditor: "Kurokawa",
    originalEditor: "Shūeisha",
    publishingMagazine: "Young Jump",
    numbersOfVolumesJapan: "14",
    numbersOfVolumesFrance: "14",
    publicationDatesJapan: "Depuis 2020",
    publicationDatesFrance: "Depuis 2023",
    dateAdded: "2024-04-21",
    notation: 8,
    notationDate: "2024-04-21",
    reviewDate: "Mai",
    summary:
      "Un médecin se réincarne dans le fils d’une idol qu’il admirait. Il découvre les coulisses impitoyables du show-business et cherche à protéger ceux qu’il aime.",
    quickSummary:
      "Un médecin se réincarne dans le fils d’une idol qu’il admirait. Il découvre les coulisses impitoyables du show-business et cherche à protéger ceux qu’il aime.",
  },
  {
    id: 37,
    title: "Ao ashi",
    originalTitle: "葬送のフリーレン",
    img: "/src/img/ao-ashi-t01-672b4b5395279701631863.webp",
    author: "Yûgo KOBAYASHI, Naohiko UENO , Yûgo KOBAYASHI",
    genre: "Sport, Tranche-de-vie",
    type: "Seinen",
    themes: "Football, Sport, Tournois",
    frenchEditor: "Mangetsu",
    originalEditor: "Shogakukan",
    publishingMagazine: "Big Comic Spirits",
    numbersOfVolumesJapan: "40",
    numbersOfVolumesFrance: "32",
    publicationDatesJapan: "2015",
    publicationDatesFrance: "Depuis 2021",
    dateAdded: "2024-04-21",
    notation: 9.6,
    notationDate: "2026-01-31",
    reviewDate: "January",
    summary:
      "Aoi Ashito habite à Ehime. Bien qu'il soit un joueur avec un grand talent pour le football, il souffre d'un caractère trop droit et impulsif. Après avoir été témoin des compétences de Ashito, Tatsuya Fukuda, directeur de l'équipe jeunesse d'Ehime, le recommande à la sélection d'une équipe organisée à Tokyo! Comment évoluera le destin de ce garçon qui révolutionnera le football ?",
    quickSummary:
      "Aoi Ashito habite à Ehime. Bien qu'il soit un joueur avec un grand talent pour le football, il souffre d'un caractère trop droit et impulsif.",
  },
  {
    id: 38,
    title: "Platinum End",
    originalTitle: "プラチナエンド",
    img: "/src/img/platinum-end-1-kaze.webp",
    author: "Tsugumi Ohba & Takeshi Obata",
    genre: "Thriller, surnaturel",
    type: "Shonen",
    themes: "Anges, Concours, Morale, Destin",
    frenchEditor: "Kazé",
    originalEditor: "Shūeisha",
    publishingMagazine: "Jump SQ",
    numbersOfVolumesJapan: "14",
    numbersOfVolumesFrance: "14",
    publicationDatesJapan: "2015 - 2021",
    publicationDatesFrance: "2016 - 2022",
    dateAdded: "2024-04-21",
    notation: 7.5,
    notationDate: "2026-01-31",
    reviewDate: "January",
    summary:
      "Mirai reçoit des pouvoirs d’un ange et se retrouve impliqué dans une compétition mortelle pour devenir le prochain dieu. Chaque candidat possède ses propres motivations, parfois terrifiantes.",
    quickSummary:
      "Mirai reçoit des pouvoirs d’un ange et se retrouve impliqué dans une compétition mortelle pour devenir le prochain dieu. Chaque candidat possède ses propres motivations, parfois terrifiantes.",
  },
  {
    id: 39,
    title: "A Silent Voice",
    originalTitle: "聲の形",
    img: "/src/img/a-silent-voice-1-ki-oon.webp",
    author: "Yoshitoki Ōima",
    genre: "Drame, tranche de vie",
    type: "Shonen",
    themes: "Handicap, Rédemption, Adolescence, Relations humaines",
    frenchEditor: "Ki-oon",
    originalEditor: "Kodansha",
    publishingMagazine: "Weekly Shōnen Magazine",
    numbersOfVolumesJapan: "7",
    numbersOfVolumesFrance: "7",
    publicationDatesJapan: "2013 - 2014",
    publicationDatesFrance: "2015 - 2016",
    dateAdded: "2024-04-21",
    notation: 9.4,
    notationDate: "2026-02-01",
    reviewDate: "February",
    summary:
      "Shoya cherche à se racheter après avoir harcelé une camarade sourde durant son enfance. Leur rencontre des années plus tard bouleverse leurs vies et ouvre la voie à un long chemin de pardon.",
    quickSummary:
      "Shoya cherche à se racheter après avoir harcelé une camarade sourde durant son enfance. Leur rencontre des années plus tard bouleverse leurs vies et ouvre la voie à un long chemin de pardon.",
  },
  {
    id: 40,
    title: "Beastars",
    originalTitle: "ビースターズ",
    img: "/src/img/Beastars-1-kioon.webp",
    author: "Paru Itagaki",
    genre: "Drame, psychologie",
    type: "Shonen",
    themes: "Société animale, Préjugés, Identité, Violence",
    frenchEditor: "Ki-oon",
    originalEditor: "Akita Shoten",
    publishingMagazine: "Weekly Shōnen Champion",
    numbersOfVolumesJapan: "22",
    numbersOfVolumesFrance: "22",
    publicationDatesJapan: "2016 - 2020",
    publicationDatesFrance: "2019 - 2023",
    dateAdded: "2024-04-21",
    notation: 8.3,
    notationDate: "2026-02-02",
    reviewDate: "February",
    summary:
      "Dans un monde d’animaux anthropomorphes, Legoshi, un loup timide, lutte contre ses instincts et les tensions entre carnivores et herbivores. Une enquête sur un meurtre bouleverse son quotidien.",
    quickSummary:
      "Dans un monde d’animaux anthropomorphes, Legoshi, un loup timide, lutte contre ses instincts et les tensions entre carnivores et herbivores. Une enquête sur un meurtre bouleverse son quotidien.",
  },
  {
    id: 41,
    title: "Gantz",
    originalTitle: "ガンツ",
    img: "/src/img/gantz_01.webp",
    author: "Hiroya Oku",
    genre: "Science-fiction, horreur",
    type: "Seinen",
    themes: "Mort, Violence, Extraterrestres, Survie",
    frenchEditor: "Kana",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Young Jump",
    numbersOfVolumesJapan: "37",
    numbersOfVolumesFrance: "37",
    publicationDatesJapan: "2000 - 2013",
    publicationDatesFrance: "2002 - 2014",
    dateAdded: "2024-04-21",
    notation: 8.1,
    notationDate: "2026-02-02",
    reviewDate: "February",
    summary:
      "Après leur mort, Kei et Masaru sont forcés de participer à des missions violentes orchestrées par une mystérieuse sphère noire. Ils doivent éliminer des créatures pour espérer survivre.",
    quickSummary:
      "Après leur mort, Kei et Masaru sont forcés de participer à des missions violentes orchestrées par une mystérieuse sphère noire. Ils doivent éliminer des créatures pour espérer survivre.",
  },
  {
    id: 42,
    title: "20th Century Boys",
    originalTitle: "20世紀少年",
    img: "/src/img/20th-century-boys-tome-1-670d35fd617be896837284.webp",
    author: "Naoki Urasawa",
    genre: "Thriller, mystère",
    type: "Seinen",
    themes: "Sectes, Enfance, Conspiration, Destin",
    frenchEditor: "Panini",
    originalEditor: "Shogakukan",
    publishingMagazine: "Big Comic Spirits",
    numbersOfVolumesJapan: "22",
    numbersOfVolumesFrance: "22",
    publicationDatesJapan: "1999 - 2006",
    publicationDatesFrance: "2001 - 2007",
    dateAdded: "2024-04-21",
    notation: 9.5,
    notationDate: "2026-02-02",
    reviewDate: "February",
    summary:
      "Kenji découvre qu’un culte mystérieux utilise un symbole qu’il avait inventé enfant. Il tente de comprendre comment un simple jeu d’enfants a pu devenir une menace mondiale.",
    quickSummary:
      "Kenji découvre qu’un culte mystérieux utilise un symbole qu’il avait inventé enfant. Il tente de comprendre comment un simple jeu d’enfants a pu devenir une menace mondiale.",
  },
  {
    id: 43,
    title: "The Ancient Magus Bride",
    originalTitle: "魔法使いの嫁",
    img: "/src/img/The-Ancient-Magus-Bride-1-komikku.webp",
    author: "Kore Yamazaki",
    genre: "Fantasy, romance",
    type: "Seinen",
    themes: "Magie, Créatures, Solitude, Destin",
    frenchEditor: "Komikku",
    originalEditor: "Mag Garden",
    publishingMagazine: "Monthly Comic Garden",
    numbersOfVolumesJapan: "20",
    numbersOfVolumesFrance: "20",
    publicationDatesJapan: "Depuis 2013",
    publicationDatesFrance: "Depuis 2015",
    dateAdded: "2024-04-21",
    notation: 8.4,
    notationDate: "2026-02-03",
    reviewDate: "February",
    summary:
      "Chise, vendue aux enchères, devient l’apprentie d’un mage non humain. Elle découvre un monde magique aussi dangereux que fascinant, et apprend à se reconstruire.",
    quickSummary:
      "Chise, vendue aux enchères, devient l’apprentie d’un mage non humain. Elle découvre un monde magique aussi dangereux que fascinant, et apprend à se reconstruire.",
  },
  {
    id: 44,
    title: "Ajin",
    originalTitle: "亜人",
    img: "/src/img/ajin-1-glenat.webp",
    author: "Gamon Sakurai",
    genre: "Action, surnaturel",
    type: "Seinen",
    themes: "Immortalité, Gouvernement, Expériences, Fuite",
    frenchEditor: "Glénat",
    originalEditor: "Kodansha",
    publishingMagazine: "Good! Afternoon",
    numbersOfVolumesJapan: "17",
    numbersOfVolumesFrance: "17",
    publicationDatesJapan: "2012 - 2021",
    publicationDatesFrance: "2014 - 2022",
    dateAdded: "2024-04-21",
    notation: 8,
    notationDate: "2026-02-03",
    reviewDate: "February",
    summary:
      "Kei découvre qu’il est un Ajin, un être immortel traqué par le gouvernement. Il doit fuir et comprendre les pouvoirs mystérieux qui l’habitent.",
    quickSummary:
      "Kei découvre qu’il est un Ajin, un être immortel traqué par le gouvernement. Il doit fuir et comprendre les pouvoirs mystérieux qui l’habitent.",
  },
  {
    id: 45,
    title: "Noragami",
    originalTitle: "ノラガミ",
    img: "/src/img/noragami-t01-673db5f1cfce8650676395.webp",
    author: "Adachitoka",
    genre: "Action, surnaturel",
    type: "Shonen",
    themes: "Dieux, Esprits, Amitié, Identité",
    frenchEditor: "Pika",
    originalEditor: "Kodansha",
    publishingMagazine: "Monthly Shōnen Magazine",
    numbersOfVolumesJapan: "27",
    numbersOfVolumesFrance: "27",
    publicationDatesJapan: "Depuis 2010",
    publicationDatesFrance: "Depuis 2013",
    dateAdded: "2024-04-21",
    notation: 9.2,
    notationDate: "2026-02-03",
    reviewDate: "February",
    summary:
      "Yato, un dieu mineur sans temple, rêve de devenir célèbre. Avec Hiyori et Yukine, il affronte des esprits corrompus et son propre passé.",
    quickSummary:
      "Yato, un dieu mineur sans temple, rêve de devenir célèbre. Avec Hiyori et Yukine, il affronte des esprits corrompus et son propre passé.",
  },
  {
    id: 46,
    title: "Black Butler",
    originalTitle: "黒執事",
    img: "/src/img/black-butler-tome-1-673dd7040d3c1531818448.webp",
    author: "Yana Toboso",
    genre: "Mystère, dark fantasy",
    type: "Shonen",
    themes: "Démons, Angleterre victorienne, Enquête, Pacte",
    frenchEditor: "Kana",
    originalEditor: "Square Enix",
    publishingMagazine: "Monthly GFantasy",
    numbersOfVolumesJapan: "33",
    numbersOfVolumesFrance: "33",
    publicationDatesJapan: "Depuis 2006",
    publicationDatesFrance: "Depuis 2009",
    dateAdded: "2024-04-21",
    notation: 8.3,
    notationDate: "2026-02-03",
    reviewDate: "February",
    summary:
      "Ciel Phantomhive, jeune comte au passé tragique, résout des affaires pour la reine grâce à Sebastian, son majordome démoniaque lié par un pacte.",
    quickSummary:
      "Ciel Phantomhive, jeune comte au passé tragique, résout des affaires pour la reine grâce à Sebastian, son majordome démoniaque lié par un pacte.",
  },
  {
    id: 47,
    title: "Soul Eater",
    originalTitle: "ソウルイーター",
    img: "/src/img/soul-eater-01.webp",
    author: "Atsushi Ōkubo",
    genre: "Action, dark fantasy",
    type: "Shonen",
    themes: "Démons, École, Armes vivantes, Amitié",
    frenchEditor: "Kurokawa",
    originalEditor: "Square Enix",
    publishingMagazine: "Monthly Shōnen Gangan",
    numbersOfVolumesJapan: "25",
    numbersOfVolumesFrance: "25",
    publicationDatesJapan: "2004 - 2013",
    publicationDatesFrance: "2009 - 2014",
    dateAdded: "2024-04-21",
    notation: 8.1,
    notationDate: "2026-02-03",
    reviewDate: "February",
    summary:
      "À la Death Weapon Meister Academy, Maka et Soul doivent récolter des âmes pour transformer Soul en arme ultime. Leur parcours les mène à affronter des sorcières et des forces chaotiques.",
    quickSummary:
      "À la Death Weapon Meister Academy, Maka et Soul doivent récolter des âmes pour transformer Soul en arme ultime. Leur parcours les mène à affronter des sorcières et des forces chaotiques.",
    quickSummary:
      "https://www.fnac.com/a2607750/Soul-Eater-Tome-1-Soul-Eater-Okubo-Atsushi",
  },
  {
    id: 48,
    title: "Fruits Basket",
    originalTitle: "フルーツバスケット",
    img: "/src/img/fruits_basket_01.webp",
    author: "Natsuki Takaya",
    genre: "Romance, Drame, Fantastique",
    type: "Shojo",
    themes: "Famille, Malédiction, Amitié, Amour",
    frenchEditor: "Delcourt/Tonkam",
    originalEditor: "Hakusensha",
    publishingMagazine: "Hana to Yume",
    numbersOfVolumesJapan: "23",
    numbersOfVolumesFrance: "23",
    publicationDatesJapan: "1998–2006",
    publicationDatesFrance: "2009 - 2014",
    dateAdded: "2026–05-02",
    notation: 9.1,
    notationDate: "2024-05-03",
    reviewDate: "February",
    summary:
      "Une lycéenne découvre qu’une famille est frappée d’une malédiction les transformant en animaux du zodiaque chinois.",
    quickSummary:
      "https://www.fnac.com/a1306919/Fruits-Basket-Tome-1-Fruits-Basket-Natsuki-Takaya",
  },
  {
    id: 49,
    title: "Yo-kai Watch",
    originalTitle: "妖怪ウォッチ",
    img: "/src/img/yokai-watch-1-kaze.webp",
    author: "Noriyuki Konishi",
    genre: "Aventure, Comédie",
    type: "Kodomo",
    themes: "Esprits, Amitié, Humour",
    frenchEditor: "Kazé",
    originalEditor: "Shogakukan",
    publishingMagazine: "CoroCoro Comic",
    numbersOfVolumesJapan: "20",
    numbersOfVolumesFrance: "20",
    publicationDatesJapan: "2013–2019",
    publicationDatesFrance: "2013–2019",
    dateAdded: "2026-05-03",
    notation: 7.9,
    notationDate: "2025-05-03",
    reviewDate: "February",
    summary:
      "Un garçon obtient une montre lui permettant de voir et d’aider des créatures appelées Yo-kai.",
    quickSummary:
      "Un garçon obtient une montre lui permettant de voir et d’aider des créatures appelées Yo-kai.",
    urlFnac:
      "https://www.fnac.com/a10086370/Yo-Kai-Watch-Tome-01-Yo-Kai-Watch-Noriyuki-Konishi",
  },
  {
    id: 50,
    title: "Sword Art Online",
    originalTitle: "ソードアート・オンライン",
    img: "/src/img/sword-art-online-roman-vol1-ofelbe.webp",
    author: "Reki Kawahara",
    genre: "Action, Science-fiction",
    type: "Light Novel",
    themes: "MMORPG, Réalité virtuelle, Survie",
    frenchEditor: "Ofelbe",
    originalEditor: "Shogakukan",
    publishingMagazine: "ASCII Media Works",
    numbersOfVolumesJapan: "27",
    numbersOfVolumesFrance: "20",
    publicationDatesJapan: "2009",
    publicationDatesFrance: "2015",
    dateAdded: "2026-05-03",
    notation: 8.4,
    notationDate: "2025-05-03",
    reviewDate: "February",
    summary:
      "Des joueurs sont piégés dans un MMORPG où mourir en jeu signifie mourir dans la réalité.",
    quickSummary:
      "Des joueurs sont piégés dans un MMORPG où mourir en jeu signifie mourir dans la réalité.",
    urlFnac:
      "https://www.fnac.com/a7958545/Sword-Art-Online-Tome-1-Sword-Art-Online-tome-1-Aincrad-Reki-Kawahara",
  },
  {
    id: 51,
    title: "Re:Zero – Starting Life in Another World",
    originalTitle: "Re:ゼロから始める異世界生活",
    img: "/src/img/re-zer-roman-arc-1-1-ofelbe.webp",
    author: "Tappei Nagatsuki",
    genre: "Isekai, Drame, Fantastique",
    type: "Light Novel",
    themes: "Boucle temporelle, Tragédie, Héroïsme",
    frenchEditor: "Ofelbe",
    originalEditor: "Shogakukan",
    publishingMagazine: "Media Factory",
    numbersOfVolumesJapan: "35",
    numbersOfVolumesFrance: "20",
    publicationDatesJapan: "2014-",
    publicationDatesFrance: "2016-",
    dateAdded: "2026-05-03",
    notation: 9,
    notationDate: "2025-05-03",
    reviewDate: "February",
    summary:
      "Subaru est transporté dans un autre monde et découvre qu’il peut revenir à la vie après chaque mort.",
    quickSummary:
      "Subaru est transporté dans un autre monde et découvre qu’il peut revenir à la vie après chaque mort.",
    urlFnac:
      "https://www.fnac.com/a10232224/Re-Zero-Tome-01-Re-zero-Tappei-Nagatsuki",
  },
  {
    id: 52,
    title: "Skip Beat!",
    originalTitle: "スキップ・ビート!",
    img: "/src/img/Skip_Beat_01.webp",
    author: "Yoshiki Nakamura",
    genre: "Romance, Comédie, Drame",
    type: "Shojo",
    themes: "Showbiz, Vengeance, Développement personnel",
    frenchEditor: "Delcourt/Tonkam",
    originalEditor: "Hakusensha",
    publishingMagazine: "Hana to Yume",
    numbersOfVolumesJapan: "49",
    numbersOfVolumesFrance: "49",
    publicationDatesJapan: "2002",
    publicationDatesFrance: "2006",
    dateAdded: "2026-05-03",
    notation: 8.9,
    notationDate: "2025-05-03",
    reviewDate: "February",
    summary:
      "Une jeune femme entre dans le monde du showbiz pour se venger de son ex-idole.",
    quickSummary:
      "Une jeune femme entre dans le monde du showbiz pour se venger de son ex-idole.",
    urlFnac:
      "https://www.fnac.com/a2242565/Skip-Beat-Tome-1-Skip-Beat-Yoshiki-Nakamura",
  },
  {
    id: 53,
    title: "Nana",
    originalTitle: "ナナ",
    img: "/src/img/nana_01.webp",
    author: "Ai Yazawa",
    genre: "Romance, Drame, Slice of life",
    type: "Shojo",
    themes: "Musique, Amitié, Relations adultes",
    frenchEditor: "Delcourt/Tonkam",
    originalEditor: "Shueisha",
    publishingMagazine: "Cookie",
    numbersOfVolumesJapan: "21",
    numbersOfVolumesFrance: "21",
    publicationDatesJapan: "2000",
    status: "en pause",
    publicationDatesFrance: "2002-2016",
    dateAdded: "2026-05-03",
    notation: 9.3,
    notationDate: "2024-05-03",
    reviewDate: "February",
    summary:
      "Deux jeunes femmes nommées Nana voient leurs destins s’entremêler dans un Tokyo vibrant.",
    quickSummary:
      "Deux jeunes femmes nommées Nana voient leurs destins s’entremêler dans un Tokyo vibrant.",
    urlFnac: "https://www.fnac.com/a1333541/Nana-Tome-1-Tome-01-Nana-Ai-Yazawa",
  },
  {
    id: 54,
    title: "Monster",
    originalTitle: "モンスター",
    img: "/src/img/monster-deluxe-1-kana.webp",
    author: "Naoki Urasawa",
    genre: "Thriller, Psychologique, Drame",
    type: "Seinen",
    themes: "Meurtre, Enquête, Psychologie, Morale",
    frenchEditor: "Kana",
    originalEditor: "Shogakukan",
    publishingMagazine: "Big Comic Original",
    numbersOfVolumesJapan: "18",
    numbersOfVolumesFrance: "18",
    publicationDatesJapan: "1994–2001",
    status: "terminé",
    publicationDatesFrance: "2002–2006",
    dateAdded: "2026-02-18",
    notation: 9.4,
    notationDate: "2026-02-18",
    reviewDate: "February",
    summary:
      "Un neurochirurgien sauve un enfant qui deviendra un tueur en série ; il part à sa poursuite pour réparer son erreur.",
    quickSummary:
      "Un médecin traque la créature qu’il a involontairement libérée.",
    urlFnac:
      "https://www.fnac.com/a3086201/Monster-Tome-1-Monster-Integrale-Deluxe-Naoki-Urasawa",
  },
  {
    id: 55,
    title: "Vagabond",
    originalTitle: "バガボンド",
    img: "/src/img/vagabond_01.webp",
    author: "Takehiko Inoue",
    genre: "Historique, Action, Drame",
    type: "Seinen",
    themes: "Samouraï, Quête, Philosophie, Combat",
    frenchEditor: "Glénat",
    originalEditor: "Kodansha",
    publishingMagazine: "Morning",
    numbersOfVolumesJapan: "37",
    numbersOfVolumesFrance: "37",
    publicationDatesJapan: "1998",
    status: "en pause",
    publicationDatesFrance: "2002",
    dateAdded: "2026-02-18",
    notation: 9,
    notationDate: "2026-02-18",
    reviewDate: "February",
    summary:
      "La vie romancée du légendaire samouraï Miyamoto Musashi, entre combats et recherche de sens.",
    quickSummary:
      "Portrait épique et contemplatif d’un samouraï en quête de perfection.",
    urlFnac:
      "https://www.fnac.com/a1188829/Vagabond-Tome-01-Vagabond-Takehiko-Inoue",
  },
  {
    id: 56,
    title: "Blue Spring Ride",
    originalTitle: "アオハライド",
    img: "/src/img/blue-spring-ride-1-kana.webp",
    author: "Io Sakisaka",
    genre: "Romance, Slice of life, Drame",
    type: "Shojo",
    themes: "Lycée, Amour, Renouveau, Amitié",
    frenchEditor: "Delcourt/Tonkam",
    originalEditor: "Shueisha",
    publishingMagazine: "Bessatsu Margaret",
    numbersOfVolumesJapan: "13",
    numbersOfVolumesFrance: "13",
    publicationDatesJapan: "2011–2015",
    status: "terminé",
    publicationDatesFrance: "2013–2016",
    dateAdded: "2026-02-18",
    notation: 8.2,
    notationDate: "2026-02-18",
    reviewDate: "February",
    summary:
      "Sawako, mal comprise à cause de son apparence, se lie d’amitié et découvre l’amour grâce à ses camarades.",
    quickSummary: "Histoire douce d’une jeune fille qui s’ouvre au monde.",
    urlFnac:
      "https://www.fnac.com/a5786078/Blue-spring-ride-Tome-1-Blue-Spring-Ride-Io-Sakisaka",
  },
  {
    id: 57,
    title: "One piece Tome 2",
    originalTitle: "ワンピース",
    img: "/src/img/one-piece-edition-originale-2-glenat.webp",
    author: "Eiichiro Oda",
    genre: "Aventure, Action, Fantaisie",
    type: "Shonen",
    themes: "Pirates, Liberté, Amitié, Trésor",
    frenchEditor: "Glénat",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Shōnen Jump",
    numbersOfVolumesJapan: "113",
    numbersOfVolumesFrance: "111",
    publicationDatesJapan: "Depuis 1997",
    publicationDatesFrance: "Depuis 2000",
    dateAdded: "2026-02-18",
    notation: 9.9,
    notationDate: "2026-02-18",
    reviewDate: "February",
    summary:
      "Nous sommes à l'ère des pirates. Luffy, un garçon espiègle, rêve de devenir le roi des pirates en trouvant le “One Piece”, un fabuleux trésor. Seulement, Luffy a avalé un fruit du démon qui l'a transformé en homme élastique. Depuis, il est capable de contorsionner son corps dans tous les sens, mais il a perdu la faculté de nager. Avec l'aide de ses précieux amis, il va devoir affronter de redoutables pirates dans des aventures toujours plus rocambolesques.Également adapté en dessin animé pour la télévision et le cinéma, One Piece remporte un formidable succès à travers le monde. Les aventures de Luffy au chapeau de paille ont désormais gagné tous les lecteurs, qui se passionnent chaque trimestre pour les aventures exceptionnelles de leurs héros.",
    quickSummary:
      "Nous sommes à l'ère des pirates. Luffy, un garçon espiègle, rêve de devenir le roi des pirates en trouvant le “One Piece”, un fabuleux trésor",
    urlFnac:
      "https://www.fnac.com/a5843685/One-Piece-Luffy-versus-la-bande-a-Baggy-Tome-02-One-Piece-Edition-originale-Eiichiro-Oda",
  },
  {
    id: 58,
    title: "Bonne nuit Punpun Tome 1",
    originalTitle: "おやすみプンプン",
    img: "/src/img/bonne-nuit-punpun-tome-1-6728a0e52435e933698709.webp",
    author: "Inio Asano",
    genre: "Drame, Psychologie, Slice of Life",
    type: "Seinen",
    themes: "Solitude, Famille, Dépression, Adolescence",
    frenchEditor: "Kana",
    originalEditor: "Shogakukan",
    publishingMagazine: "Weekly Young Sunday",
    numbersOfVolumesJapan: "13",
    numbersOfVolumesFrance: "13",
    publicationDatesJapan: "2007 - 2013",
    publicationDatesFrance: "2016 - 2018",
    dateAdded: "2026-02-18",
    notation: 9.7,
    notationDate: "2026-02-18",
    reviewDate: "February",
    summary:
      "Punpun Onodera, un jeune garçon représenté sous forme d’oiseau stylisé, traverse les épreuves de la vie entre rêves, désillusions et douleurs silencieuses. À travers son regard, le lecteur découvre une histoire profondément humaine, parfois sombre, mais toujours touchante, qui explore la fragilité de l’enfance et la complexité du passage à l’âge adulte.",
    quickSummary:
      "Punpun, un garçon sensible, affronte les difficultés de la vie dans un récit poignant et introspectif.",
    urlFnac:
      "https://www.fnac.com/a3827262/Bonne-nuit-Punpun-Tome-1-Bonne-Nuit-Punpun-Inio-Asano",
  },
  {
    id: 59,
    title: "Gintama Tome 1",
    originalTitle: "銀魂",
    img: "/src/img/gintama_01.webp",
    author: "Hideaki Sorachi",
    genre: "Action, Comédie, Science-fiction",
    type: "Shonen",
    themes: "Samouraïs, Aliens, Parodie, Amitié",
    frenchEditor: "Kana",
    originalEditor: "Shūeisha",
    publishingMagazine: "Weekly Shōnen Jump",
    numbersOfVolumesJapan: "77",
    numbersOfVolumesFrance: "77",
    publicationDatesJapan: "2004 - 2019",
    publicationDatesFrance: "2007 - 2021",
    dateAdded: "2026-02-18",
    notation: 9.3,
    notationDate: "2026-02-18",
    reviewDate: "February",
    summary:
      "Dans un Japon alternatif envahi par les extraterrestres Amanto, Gintoki Sakata, un ancien samouraï excentrique, tente de survivre en acceptant toutes sortes de petits boulots. Accompagné de Shinpachi et Kagura, il se retrouve embarqué dans des aventures aussi absurdes qu’épiques, mêlant humour déjanté et combats spectaculaires.",
    quickSummary:
      "Gintoki, samouraï fainéant, survit dans un Japon envahi par les aliens en acceptant des missions loufoques.",
    urlFnac:
      "https://www.fnac.com/a1932032/Gintama-Tome-1-Tome-1-Gintama-Hideaki-Sorachi",
  },
  {
    id: 60,
    title: "La Voie du Tablier Tome 1",
    originalTitle: "極主夫道",
    img: "/src/img/voie-tablier-1-kana.webp",
    author: "Kousuke Oono",
    genre: "Comédie, Slice of Life",
    type: "Seinen",
    themes: "Yakuza, Vie domestique, Humour",
    frenchEditor: "Kurokawa",
    originalEditor: "Shinchosha",
    publishingMagazine: "Kurage Bunch",
    numbersOfVolumesJapan: "14",
    numbersOfVolumesFrance: "12",
    publicationDatesJapan: "Depuis 2018",
    publicationDatesFrance: "Depuis 2020",
    dateAdded: "2026-02-18",
    notation: 9.0,
    notationDate: "2026-02-18",
    reviewDate: "February",
    summary:
      "Tatsu, ancien yakuza légendaire surnommé 'le Dragon Immortel', a abandonné le crime pour devenir homme au foyer. Malgré son apparence intimidante et ses réflexes de mafieux, il s’efforce de gérer les tâches domestiques avec un sérieux démesuré, créant des situations hilarantes et décalées.",
    quickSummary:
      "Tatsu, ex-yakuza redouté, devient un mari au foyer ultra-dévoué dans une comédie irrésistible.",
    urlFnac:
      "https://www.fnac.com/a13358306/La-Voie-Du-Tablier-Tome-1-La-voie-du-tablier-Kousuke-Oono",
  },
];

